package-lock.json
package.json
yarn.lock

-  Removed "@openzeppelin/cli" package because this package is not used and is generating vulnerabilities 
- Fix some npm audit issues

 Removed "@openzeppelin/cli" package 

---

package.json
src/chains.ts

wagmi rpc has changed https://twitter.com/_patrickogrady/status/1505673648866152452?s=21&t=lgyyC5gJi51VnLCc7PRKcg , updates sdk accordingly

wagmi rpc changed 

---

src/chains.ts

Renamed CHAINS array to ALL_CHAINS 
Added CHAINS as object

Renamed CHAINS to ALL_CHAINS

---

src/chains.ts

Updated Fuji contracts so we can test functionality on testnet before mass deployment

Updated Fuji contracts

---

src/chains.ts

Includes Avalanche mainnet exchange subgraph reference

Add Subgraph Reference

---

package.json
src/chains.ts

new addresses (hopefuly the final one for wagmi and coston)

New addresses wagmi/coston

---

src/chains.ts

non-evm update only need put the chainId in option

Non evm update

---

src/chains.ts

Old rpc not work, changed to new rpc url 
Added deploy contracts

Fix polygon mumbai and add contract

---

src/constants.ts
src/entities/pair.ts

Allow each chain to specify the pool2 pair swap fees

Swap fee mappings

---

src/chains.ts

Added sar contract

---

src/chains.ts

Updated coston airdrop contract address
Updated consto, flare and songbird png symbol

Update airdrop contract address and png symbol

---

package.json
src/chains.ts
src/constants.ts
src/entities/currency.ts
src/entities/token.ts

add songbird to chains & chainid

---

package.json
yarn.lock

- upgrade @pangolindex/exchange-contracts & add resolution so it doesn't use @pangolindex/exchange-contracts@1.x.x

upgrade exchange-contracts to 2.1.4

---

src/chains.ts

```
0x02f0826ef6aD107Cfc861152B32B52fD11BaB9ED : WAVAX
0x3AAD4eE30d41525c2Ee7D0F4070ebF31568F31b4 : Png
0x56a7F4597D8ee5d4Af13f7063b507E4Dc7D0099c : MultiSigWalletWithDailyLimit
0x987a31C27Dc3685C1cDFBE58635Eb1379181D886 : Timelock
0xe8E23105C0D394bE611dC7516E7dF9D52B2Ec744 : PangolinFactory
0xb16711146c6E669CBCA71d4ae3E1d2c86A2cAb3C : PangolinRouter
0x4DbD504D19ce7557b9F88091199b9a1Cfe8c5F72 : CommunityTreasury
0x482FC8A1d418e3C4BC73C0E7fE0fA62eAB0df8dc : PangoChef
0x243B96Ea067AABc3bEAa96A89d43a3d13aDe7E41 : RewardFundingForwarder
0xc9c122faB41939df9D0e0326fA6895A989E25cB7 : TokenMetadata
0xcf46391024803368eA169c5F5cE6eDa622Cb577c : PangolinStakingPositions
0x867408682e98FF410A47f2bb2a3539eb983D5BF7 : RewardFundingForwarder
0xa3ffE2CE452C23941b62B5D570f36b823E1e0D0F : …
```

update songbird contract addresses

---

src/chains.ts

```
0x02f0826ef6aD107Cfc861152B32B52fD11BaB9ED : WAVAX
0xb2987753D1561570f726Aa373F48E77e27aa5FF4 : Png
0xe18dFC20edE326930d11b3316E92bdC1F606dc94 : MultiSigWalletWithDailyLimit
0xF92F8A011A55C243CBAA096A62d9C48880070af6 : Timelock
0xB66E62b25c42D55655a82F8ebf699f2266f329FB : PangolinFactory
0x6591cf4E1CfDDEcB4Aa5946c033596635Ba6FB0F : PangolinRouter
0xA2e6eFFdbb278744E286F602Bfaa2BcDAccBb1AA : CommunityTreasury
0x76489156Fff6f4B89626f58386366941150642B7 : PangoChef
0x6Cf469a019eB7c7668b3f0A23c2007EFEC901cA8 : RewardFundingForwarder
0x938b8703472a3908b06C2F5B2A250FB6ABB3f256 : TokenMetadata
0x7428A089A79B24400a620F1Cbf8bd0526cFae777 : PangolinStakingPositions
0x7D3AF25AEa0E41f06735f2ce797516b8f34c3F9c : RewardFundingForwarder
0x1c4429A271ec5E36a2FDc6400A5a6e49E605dF17 : …
```

Update SongBird Adresses

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build-artifacts.yml
.github/workflows/commitlint.yml
.github/workflows/publish-internal.yml
.husky/commit-msg
commitlint.config.js
package.json
tsconfig.json
yarn.lock

- add github action for publishing internal builds & commitlint
- add pull request templates

feat: add github actions for internal build & commitlint

---

src/chains.ts
src/constants.ts
src/entities/pools/pair.ts

- mark Hedera as evm chain as we want to use evm related logic
- fix Hedera pair address creation logic by updating INIT_CODE_HASH  
- update Hedera multicall contract address

fix: hedera pair address creation logic

---

src/chains.ts

-  Replace hedera router address

fix: hedera router address

---

src/entities/pools/pair.ts

- make pair decimals 0 in hedera testnet

fix: hedera decimals pair decimals to 0

---

src/chains.ts

- update hedera testnet pangochef address

fix: hedera testnet pangochef address

---

src/chains.ts
src/constants.ts
src/entities/currency.ts
src/entities/token.ts

- Addresses of deployed contracts are added into `COSTON2_TESTNET`.
- ChainID of `Coston2 Testnet` is added into ChainId.

feat: adding deployed contracts on coston2 testnet

---

src/chains.ts
src/entities/pools/pair.ts

- fix: hedera mainnet pair decimals
- fix: hedera mainnet true
- fix: pangolin_is_live for hedera mainnet

fix: hedera mainnet pair decimals, mainnet & pangolin_is_live field

---

src/chains.ts

Integrate dTWAP by [Orbs](https://www.orbs.com/) into Pangolin and PangolinDaaS, via components library.
[TWAP repo](https://github.com/orbs-network/twap)
[TWAP UI repo](https://github.com/orbs-network/twap-ui)
[TWAP dapp example playground](https://orbs-network.github.io/twap-ui/pangolin)

fix: twap by orbs

---

src/chains.ts

- fix: update compound pool id for non png farm for hedera

fix: update compound pool id for non png farm for hedera

---

src/chains.ts

fix: add subgraph url

---

src/chains.ts

- fixed hedera compound to new pbar/hbar pool

fix: hedera compound

---

src/concentratedLiquidity/constants.ts

fix: pool init code changed

---

src/concentratedLiquidity/utils/format.ts

fix: lint-issue

---

src/concentratedLiquidity/constants.ts
src/concentratedLiquidity/utils/format.ts
src/index.ts

fix: import issue

---

src/entities/fractions/currencyAmount.ts

Added the `FromRawAmount` function into `CurrencyAmount`.

feat: fromRawAmount

---

src/entities/fractions/tokenAmount.ts

- FromRawAmount function added into `TokenAmount`

feat: fromRawAmount added into tokenAmount

---

src/concentratedLiquidity/entities/nonfungiblePositionManager.ts

fix: lint issue

---

src/concentratedLiquidity/entities/nonfungiblePositionManager.ts

=> Remove Liquidity Conc Liq - Code Refactoring

fix: remove liq code refactoring

---

src/entities/bridgeCurrency.ts

- Added `equals` and `isNative` functions.

feat: equals and isNative functions added

---

src/entities/bridgeCurrency.ts

- Fixed BridgeCurrency protected issue

fix: fixed bridgeCurrency protected issue

---

src/chains.ts

- added subgraph url for sar single staking

feat: added single staking subgraph url

---

src/chains.ts

- add governance subgraph url
- add governor assistance contract address

fix: add governance subgraph url

---

src/bridges.ts

- change thorswap logo to use thorchain logo
https://app.clickup.com/t/8677kdu9r

feat: thorswap to use thorchain logo

---

src/elixir/constants.ts

- Changed old pool init code hash

fix: changed elixir old pool init code hash

---

src/chains.ts
src/elixir/constants.ts

- Deployed Elixir into Avalanche
- https://app.clickup.com/t/866ae56yz

feat: deployed elixir into avalanche_mainnet

---

.github/workflows/CI.yml
.github/workflows/build-artifacts.yml
.github/workflows/commitlint.yml
.github/workflows/publish-internal.yml
package.json

- update node version
https://app.clickup.com/t/866agrx7y

chore: update node

---

src/chains.ts
src/constants.ts
src/elixir/constants.ts
src/entities/currency.ts
src/entities/token.ts

- Added SKALE Bellatrix Testnet
- https://app.clickup.com/t/866aebyj6

feat: add skale bellatrix testnet

---

src/chains.ts

- Add Skale Bellatrix Subgraph url

fix: update skale bellatrix subgraph

---

src/chains.ts

- Disable coston airdrop
- Added hedera airdrop

fix: update airdrops

---

package.json
src/chains.ts

Production v5.3.1

---

src/chains.ts

fix: hedera compound farm

---

src/chains.ts

Includes new contracts, GovernorPango, and new gke hosted subgraph endpoint

Hedera testnet deployment

---

package.json
src/elixir/entities/elixirTrade.ts

Production v5.3.3

---

src/chains.ts

- update hedera rpc to our rpc relayer

fix: update hedera rpc

---

src/chains.ts

- Updated hedera explorer to hashscan

fix: updated hedera explorer to hashscan

---

package.json
src/chains.ts

Production v5.3.4

---

src/elixirVaults.ts

- Fixed ElixirVault logo links

fix: elixirvaults logo links

---

src/chains.ts

- Added governance subgraph addresses

fix: updated subgraph info Coston/2

---

src/chains.ts

Fix flare to compound to new pfl/flr farm

fix: flare to compound to new pfl/flr farm

---

src/chains.ts

- Update pid to compound non png pools

feat: update flare compound farm
